### ISSUE TITLE
Doesn't work on iOS?

### ISSUE THREAD

**Issue by wmertens** [ronik-design/react-drive-in#27]
I know mobile browsers don't do autoplay, but even when clicking play/pause there is no background video on iPad.

Is that even possible?

**Comment by mshick** [comment]
This component takes the approach of embedding the specified fallback image for touch-enabled devices, since to the best of my knowledge neither android nor iOS will serve up background video in an adequate way. The fallback image would be positioned just like the video, filling and fitting the background of the page.

It's called "poster" as a parameter, or would just be the image asset you specify in your assets/videos array. If you had many videos specified, with many fallback images it would show the images on a timer, like a slideshow. Again, mimicking the video behavior.

**Comment by mshick** [comment]
@wmertens interested in if you got things working. Going to close this out, but feel free to give me any feedback.
